### ISSUE TITLE
scannet

### ISSUE THREAD

**Issue by yjh576** [NUAAXQ/MLCVNet#4]
想请问下，关于在用官方给的下载scannet数据集的代码时，由于数据集有1.3T，有时候数据下着下着，网络连接就断了。请问你有遇到过这种问题吗？  或者可以给些好的建议吗？ 谢谢你

**Comment by WangZhouTao** [comment]
@yjh576
你好，3D物体检测任务不用下载所有的数据，仅下载部分数据即可。
将下载脚本中的FILETYPES修改为：
`FILETYPES = ['.aggregation.json', '.txt', '_vh_clean_2.0.010000.segs.json', '_vh_clean_2.ply', '_vh_clean_2.labels.ply']`
即可

**Comment by yjh576** [comment]
非常感谢你的帮助，想再请教下关于SUNRGBD数据集用extract_split.m文件进行处理的时候，并没有找到train_data_idx.txt，val_data_idx.txt这两个文件。请问下这种情况一般怎么解决呢

**Comment by NUAAXQ** [comment]
@yjh576 
关于这个问题，可以参考下面这个链接：https://zhuanlan.zhihu.com/p/340075483

**Comment by yjh576** [comment]
解决了，谢谢~
