### ISSUE TITLE
Can't open demo_files/pretrained_mlcvnet_on_scannet.tar 

### ISSUE THREAD

**Issue by 123jyw** [NUAAXQ/MLCVNet#9]
Can't  run   python eval.py --checkpoint_path demo_files/pretrained_mlcvnet_on_scannet.tar --dump_dir eval_scannet --use_3d_nms --use_cls_nms --per_class_proposal
The pretrained_mlcvnet_on_scannet.tar can't  be  decompressed

**Comment by 123jyw** [comment]
Can you provide me with a new compressed package?  thank you!

**Comment by NUAAXQ** [comment]
> Can't run python eval.py --checkpoint_path demo_files/pretrained_mlcvnet_on_scannet.tar --dump_dir eval_scannet --use_3d_nms --use_cls_nms --per_class_proposal The pretrained_mlcvnet_on_scannet.tar can't be decompressed

what kind of error does the code throw?

**Comment by 123jyw** [comment]
Before that.When I run this sentence CUDA_VISIBLE_DEVICES=0 python train.py, the following error will appear 
 import pointnet2_utils
  File "/home/z/wen/MLCV/MLCVNet-master/pointnet2/pointnet2_utils.py", line 30, in <module>
    "Could not import _ext module.\n"
ImportError: Could not import _ext module.
Please see the setup instructions in the README: https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/README.rst

**Comment by NUAAXQ** [comment]
> Could not import _ext module

https://github.com/facebookresearch/votenet/issues/64
Maybe this can help you.

**Comment by 123jyw** [comment]
> > 无法导入_ext模块
> 
> [facebookresearch/votenet#64](https://github.com/facebookresearch/votenet/issues/64) 也许这可以帮助你。

thank you!
